import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Geologica,
  Roboto,
  EB_Garamond,
} from "next/font/google";
import "./globals.css";
import ScrollToTopButton from "@/utils/scrollToTopButton";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const geologica = Geologica({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${geologica.className} ${geistMono.variable} antialiased`}
      >
        <span>
        {children}
          </span>
        <ScrollToTopButton />
      </body>
    </html>
  );
}
